-- CELLERY HUB STARTS --

CREATE DATABASE CELLERY_HUB;
USE CELLERY_HUB;

-- CREATE USER IF NOT EXISTS 'DATABASE_USERNAME'@'%' IDENTIFIED BY 'DATABASE_PASSWORD';
-- GRANT ALL ON CELLERY_HUB.* TO 'DATABASE_USERNAME'@'%';

# This table is used for acquiring the MySQL write lock for a specific registry artifact
CREATE TABLE IF NOT EXISTS REGISTRY_ARTIFACT_LOCK
(
    ARTIFACT_NAME VARCHAR(255) NOT NULL,
    LOCK_COUNT    INT DEFAULT 0,
    PRIMARY KEY (ARTIFACT_NAME)
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_ORGANIZATION
(
    ORG_NAME                 VARCHAR(255)               NOT NULL,
    DESCRIPTION              BLOB,
    SUMMARY                  VARCHAR(255)                        DEFAULT "",
    WEBSITE_URL              VARCHAR(255)                        DEFAULT "",
    DEFAULT_IMAGE_VISIBILITY ENUM ("PUBLIC", "PRIVATE") NOT NULL DEFAULT "PUBLIC",
    FIRST_AUTHOR             VARCHAR(255)               NOT NULL,
    CREATED_DATE             DATETIME                   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ORG_NAME)
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_ORG_TEAM_MAPPING
(
    TEAM_ID      VARCHAR(36)  NOT NULL,
    ORG_NAME     VARCHAR(255) NOT NULL,
    TEAM_NAME    VARCHAR(255) NOT NULL,
    CREATED_DATE DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TEAM_ID),
    UNIQUE KEY (ORG_NAME, TEAM_NAME),
    FOREIGN KEY (ORG_NAME) REFERENCES REGISTRY_ORGANIZATION (ORG_NAME) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_TEAM_USER_MAPPING
(
    TEAM_ID      VARCHAR(36) NOT NULL,
    USER_UUID    VARCHAR(36) NOT NULL,
    CREATED_DATE DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TEAM_ID, USER_UUID),
    FOREIGN KEY (TEAM_ID) REFERENCES REGISTRY_ORG_TEAM_MAPPING (TEAM_ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_ARTIFACT_IMAGE
(
    ARTIFACT_IMAGE_ID VARCHAR(36)                NOT NULL,
    ORG_NAME          VARCHAR(255)               NOT NULL,
    IMAGE_NAME        VARCHAR(255)               NOT NULL,
    SUMMARY           VARCHAR(255) DEFAULT "",
    DESCRIPTION       BLOB,
    FIRST_AUTHOR      VARCHAR(255)               NOT NULL,
    VISIBILITY        ENUM ("PUBLIC", "PRIVATE") NOT NULL,
    PRIMARY KEY (ARTIFACT_IMAGE_ID),
    CONSTRAINT UC_ARTIFACT_IMG UNIQUE (ORG_NAME, IMAGE_NAME),
    FOREIGN KEY (ORG_NAME) REFERENCES REGISTRY_ORGANIZATION (ORG_NAME)
        ON DELETE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_IMAGE_TEAM_MAPPING
(
    ARTIFACT_IMAGE_ID VARCHAR(36) NOT NULL,
    TEAM_ID           VARCHAR(36) NOT NULL,
    PERMISSION        INT         NOT NULL,
    CREATED_DATE      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ARTIFACT_IMAGE_ID, TEAM_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES REGISTRY_ORG_TEAM_MAPPING (TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTIFACT_IMAGE_ID) REFERENCES REGISTRY_ARTIFACT_IMAGE (ARTIFACT_IMAGE_ID) ON DELETE CASCADE

) ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS IMAGE_KEYWORDS
(
    ARTIFACT_IMAGE_ID VARCHAR(36) NOT NULL,
    KEYWORD           VARCHAR(36) NOT NULL,
    PRIMARY KEY (ARTIFACT_IMAGE_ID, KEYWORD),
    FOREIGN KEY (ARTIFACT_IMAGE_ID) REFERENCES REGISTRY_ARTIFACT_IMAGE (ARTIFACT_IMAGE_ID)
        ON DELETE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_ARTIFACT
(
    ARTIFACT_ID       VARCHAR(36)  NOT NULL,
    ARTIFACT_IMAGE_ID VARCHAR(36)  NOT NULL,
    VERSION           VARCHAR(50)  NOT NULL,
    DESCRIPTION       BLOB,
    PULL_COUNT        INT UNSIGNED          DEFAULT 0,
    PUSH_COUNT        INT UNSIGNED          DEFAULT 0,
    LAST_AUTHOR       VARCHAR(255) NOT NULL,
    FIRST_AUTHOR      VARCHAR(255) NOT NULL,
    METADATA          BLOB         NOT NULL,
    VERIFIED          BOOL                  DEFAULT FALSE,
    STATEFUL          BOOL                  DEFAULT FALSE,
    CREATED_DATE      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ARTIFACT_ID),
    CONSTRAINT UC_ARTIFACT UNIQUE (ARTIFACT_IMAGE_ID, VERSION),
    FOREIGN KEY (ARTIFACT_IMAGE_ID) REFERENCES REGISTRY_ARTIFACT_IMAGE (ARTIFACT_IMAGE_ID)
        ON DELETE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_ARTIFACT_INGRESS
(
    ARTIFACT_ID  VARCHAR(36) NOT NULL,
    INGRESS_TYPE VARCHAR(36) NOT NULL,
    PRIMARY KEY (ARTIFACT_ID, INGRESS_TYPE),
    FOREIGN KEY (ARTIFACT_ID) REFERENCES REGISTRY_ARTIFACT (ARTIFACT_ID)
        ON DELETE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS REGISTRY_ARTIFACT_LABEL
(
    ARTIFACT_ID VARCHAR(36) NOT NULL,
    LABEL_KEY   VARCHAR(36) NOT NULL,
    LABEL_VALUE VARCHAR(36) NOT NULL,
    PRIMARY KEY (ARTIFACT_ID, LABEL_KEY),
    FOREIGN KEY (ARTIFACT_ID) REFERENCES REGISTRY_ARTIFACT (ARTIFACT_ID)
        ON DELETE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

-- CELLERY HUB ENDS --