[security]
certfile="/security/api-tls.crt"
keyfile="/security/api-tls.pem"
truststore="/security/truststore.p12"
truststorepass="ballerina"

[idp.oidc]
providerurl="https://idp.hub.cellery.io:9443"
tokenendpoint="/oauth2/token"
clientid="celleryhubapplication"
clientsecret="celleryhubapplication"

[portal]
publicurl="https://hub.cellery.io:9000"

[database]
host="mysql.hub.internal"
port=3306
default="CELLERY_HUB"
user="celleryhub"
password="celleryhub"

[filter.captcha]
secret="someSecret"
endpoint="https://www.google.com/recaptcha/api/siteverify"
engaged.paths="[{\"path\" : \"/api/0.1.0/orgs/*\", \"method\": \"get\"}]"

[idp]
introspection.endpoint="https://localhost:9443/oauth2/introspect"
username="admin"
password="admin"

[b7a.log]
level="DEBUG"
